GuestHouse/GuestHouse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('owner/', include('owner.urls')),
    path('', include('visitor.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GuestHouse/owner/urls.py
from django.urls import path
from django.urls import include, path
from. import  views


urlpatterns = [
    path('', views.index, name="index"),
    path('create-user', views.CreateUser, name="CreateUser"),
    path('login', views.loginuser, name="LoginUser"),
    path('room', views.room, name="Room "),
    path('add_room', views.add_room, name="add_room"),
    path('logoutuser', views.CustomLogout, name='logout'),
    path('logout', views.CustomLogout, name='logout'),
    path('profile', views.profile, name='adminprofile'),
    path('edit/<int:pid>', views.edit, name='edit_room'),
]

GuestHouse/owner/models.py
from django.db import models

# Create your models here.

class OwnerList(models.Model):
    name = models.CharField(max_length=30)
    phone = models.IntegerField()
    email = models.CharField(max_length=30)


class Visitor(models.Model):
    name = models.CharField(max_length=30)
    phone = models.IntegerField()
    email = models.CharField(max_length=30)

class RoomData(models.Model):
    title = models.CharField(max_length=50)
    room_id = models.CharField(max_length=15)
    floor = models.IntegerField()
    bed = models.IntegerField()
    bathroom = models.IntegerField()
    location = models.TextField()
    about = models.TextField(null=True)
    desc = models.TextField()
    prize = models.IntegerField()
    wifi = models.BooleanField(default=False)
    photo = models.ImageField(upload_to='photos/')
    updated_by = models.CharField(max_length=30, null=True)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)

class Contact(models.Model):
    username = models.CharField(max_length=30, null=True)
    name = models.CharField(max_length=30)
    email = models.CharField(max_length=20)
    subject = models.CharField(max_length=30)
    message = models.TextField()

    def __str__(self):
        return self.email
    

class BookingData(models.Model):
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=20)
    room_id = models.CharField(max_length=20)
    title = models.CharField(max_length=30)
    checkin = models.DateField()
    checkout = models.DateField()
    adult = models.IntegerField()
    chield = models.IntegerField()
    message = models.TextField()
    owner = models.CharField(max_length=30)
    updated_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.email

GuestHouse/templates/dashboard/Sidebar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - SB Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link href="{% static 'dashboard/css/styles.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="index.html">Start Bootstrap</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="#!">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>





{% block body %}{% endblock body %}







            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'dashboard/js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
</body>
</html>

GuestHouse/templates/dashboard/edit_room.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - SB Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link href="{% static 'dashboard/css/styles.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="index.html">Start Bootstrap</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="#!">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="./">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <a class="nav-link" href="./room">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Rooms
                            </a>
                            <a class="nav-link" href="./profile">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                profile
                            </a>
 

                </nav>
            </div>




            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4" style="margin-top:100px;">


                        <div class="container mt-5">
                            {% for i in room_data %}
                          <form method="POST" action="./{{i.id}}" enctype="multipart/form-data">
                              {% csrf_token %}
                              <div class="form-group">
                                  <label for="id_title">Title:</label>
                                  <input type="text" class="form-control" value="{{i.title}}" name="title" maxlength="50" required="" id="id_title">
                              </div>
                  
                              <div class="form-group">
                                  <label for="id_room_id">Room id:</label>
                                  <input type="text" class="form-control" value="{{i.room_id}}" name="room_id" maxlength="15" required="" id="id_room_id" readonly>
                              </div>
                  
                              <div class="form-group">
                                  <label for="id_floor">Floor:</label>
                                  <input type="number" class="form-control" value="{{i.floor}}" name="floor" required="" id="id_floor">
                              </div>
                  
                              <div class="form-group">
                                  <label for="id_bed">Bed:</label>
                                  <input type="number" class="form-control" value="{{i.bed}}" name="bed" required="" id="id_bed">
                              </div>
                  
                              <div class="form-group">
                                  <label for="id_bathroom">Bathroom:</label>
                                  <input type="number" class="form-control" value="{{i.bathroom}}" name="bathroom" required="" id="id_bathroom">
                              </div>
                  
                              <div class="form-group">
                                  <label for="id_location">Location:</label>
                                  <textarea class="form-control" name="location" value="{{i.location}}" rows="4" required="" id="id_location"></textarea>
                              </div>
                  
                              <div class="form-group">
                                  <label for="id_about">About:</label>
                                  <textarea class="form-control" name="about" value="{{i.about}}" rows="4" required="" id="id_about"></textarea>
                              </div>
                  
                              <div class="form-group">
                                  <label for="id_desc">Desc:</label>
                                  <textarea class="form-control" name="desc" value="{{i.desc}}" rows="4" required="" id="id_desc"></textarea>
                              </div>
                  
                              <div class="form-group">
                                  <label for="id_prize">Prize:</label>
                                  <input type="number" class="form-control" value="{{i.prize}}" name="prize" required="" id="id_prize">
                              </div>
                  
                              <div class="form-group">
                                  <label for="id_wifi">Wifi:</label>
                                  <div class="form-check">
                                      <input class="form-check-input" value="{{i.wifi}}" type="checkbox" name="wifi" id="id_wifi">
                                      <label class="form-check-label" for="id_wifi">
                                          Enable Wifi
                                      </label>
                                  </div>
                              </div>
                  
                              {% comment %} <div class="form-group">
                                  <label for="id_photo">Photo:</label>
                                  <input type="file" value="{{i.photo}}" class="form-control-file" name="photo" accept="image/*" required="" id="id_photo">
                              </div> {% endcomment %}
                  
                              <div class="form-group">
                                  <label for="id_updated_by">Updated by:</label>
                                  <input type="text" class="form-control" value="{{username}}" name="updated_by" maxlength="30" required=""id="id_updated_by" readonly>
                              </div>
                  
                              <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                            {% endfor %}
                      </div>
                  
                    </div>
                </main>


                              
            


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'dashboard/js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
    </body>
    </html>
    

GuestHouse/templates/dashboard/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Owner</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link href="{% static 'dashboard/css/styles.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="./">Ownner Page</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="/logout">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="./">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <a class="nav-link" href="./room">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Rooms
                            </a>
                            <a class="nav-link" href="./profile">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                profile
                            </a>
 

                </nav>
            </div>




            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">Dashboard</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Dashboard</li>
                        </ol>
                        
                        

                        <div class="card mb-4">
                            <div class="card-header">
                                <svg class="svg-inline--fa fa-table me-1" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="table" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg="">
                                    <path fill="currentColor" d="M64 256V160H224v96H64zm0 64H224v96H64V320zm224 96V320H448v96H288zM448 256H288V160H448v96zM64 32C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64z"></path></svg><!-- <i class="fas fa-table me-1"></i> Font Awesome fontawesome.com -->
                                DataTable Example
                            </div>
                            <div class="card-body">
                                <div class="datatable-wrapper datatable-loading no-footer sortable searchable fixed-columns">
                                    <div class="datatable-top">

    <div class="datatable-search">
            <input class="datatable-input" placeholder="Search..." type="search" title="Search within table" aria-controls="datatablesSimple">
        </div>
</div>
<div class="datatable-container">
    <table id="datatablesSimple" class="datatable-table">
        <thead>
            <tr>
                <th data-sortable="true" style="width: 20.803443328550934%;">
                    <a href="#" class="datatable-sorter">Email</a>
                </th>
                <th data-sortable="true" style="width: 22.23816355810617%;">
                    <a href="#" class="datatable-sorter">Title</a>
                </th>
                <th data-sortable="true" style="width: 14.777618364418938%;">
                    <a href="#" class="datatable-sorter">Room ID</a>
                </th>
                <th data-sortable="true" style="width: 10.473457675753227%;">
                    <a href="#" class="datatable-sorter">Start date</a>
                </th><th data-sortable="true" style="width: 17.50358680057389%;">
                    <a href="#" class="datatable-sorter">End Date</a>
                </th><th data-sortable="true" style="width: 14.203730272596843%;" aria-sort="ascending" class="datatable-ascending">
                    <a href="#" class="datatable-sorter">No of Person</a>
                </th></tr>
            </thead>
            <tbody>
                {% for i in data %}
                <tr data-index="0">
                    <td>{{i.email}}</td
                        ><td>{{i.title}}</td>
                        <td>{{i.room_id}}</td>
                        <td>{{i.checkin}}</td>
                        <td>{{i.checkout}}</td>
                        <td>{{i.adult}}</td>
                    </tr>
                {% endfor %}
       
                    
                </tbody>
            </table>
        </div>
<div class="datatable-bottom">
    
</div></div>
                            </div>
                        </div>

                        
                    </div>
                </main>


                              
            


    
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'dashboard/js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
    </body>
    </html>
    

GuestHouse/templates/dashboard/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - SB Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link href="{% static 'dashboard/css/styles.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="./">Start Bootstrap</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="/logout">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <a class="nav-link" href="./room">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Rooms
                            </a>
                            <a class="nav-link" href="./profile">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                profile
                            </a>
 

                </nav>
            </div>



            <script src="https://kit.fontawesome.com/b8b432d7d3.js" crossorigin="anonymous"></script>
            <!-- Import CSS file (style.css) -->
            <link rel="stylesheet" href="{% static 'profile/style.css' %}">
            <div class="container" style='margin-left:20%; display:flex; width:80%;' >
                {% for i in userdata %}
                <div class="profile-card">
                    <div class="profile-header">
                        <!-- profile header section -->
                        <div class="main-profile">
                            <div class="profile-image"></div>
                            <div class="profile-names">
                                <h1 class="username" style="color:#FEA116;" >{{ i.name }}</h1>
                            </div>
                        </div>
                    </div>
        
        
                    <div class="profile-body">
                        <!-- profile body section -->
                        <div class="profile-actions">
                            <button class="follow">{{ i.email }} </button>
                            <button class="follow">{{ i.phone }}</button>
                            <button class="follow">LogOut</button>
                            <!-- <button class="follow">Follow</button>
                            <button class="follow">Follow</button> -->
                        </div>
                        
                    </div>
                    {% endfor %} 
                </div>
            </div>
        
                              
            


    
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'dashboard/js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
    </body>
    </html>
    